/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as ResponsibleUseRouteImport } from './routes/responsible-use'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SoftwareRouteImport } from './routes/software'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsibleUseRoute = ResponsibleUseRouteImport.update({
  id: '/responsible-use',
  path: '/responsible-use',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareRoute = SoftwareRouteImport.update({
  id: '/software',
  path: '/software',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/devices': typeof DevicesRoute
  '/docs': typeof DocsRoute
  '/learn': typeof LearnRoute
  '/modules': typeof ModulesRoute
  '/responsible-use': typeof ResponsibleUseRoute
  '/shop': typeof ShopRoute
  '/software': typeof SoftwareRoute
  '/products/$slug': typeof ProductsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/devices': typeof DevicesRoute
  '/docs': typeof DocsRoute
  '/learn': typeof LearnRoute
  '/modules': typeof ModulesRoute
  '/responsible-use': typeof ResponsibleUseRoute
  '/shop': typeof ShopRoute
  '/software': typeof SoftwareRoute
  '/products/$slug': typeof ProductsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/devices': typeof DevicesRoute
  '/docs': typeof DocsRoute
  '/learn': typeof LearnRoute
  '/modules': typeof ModulesRoute
  '/responsible-use': typeof ResponsibleUseRoute
  '/shop': typeof ShopRoute
  '/software': typeof SoftwareRoute
  '/products/$slug': typeof ProductsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/community'
    | '/devices'
    | '/docs'
    | '/learn'
    | '/modules'
    | '/responsible-use'
    | '/shop'
    | '/software'
    | '/products/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/community'
    | '/devices'
    | '/docs'
    | '/learn'
    | '/modules'
    | '/responsible-use'
    | '/shop'
    | '/software'
    | '/products/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/community'
    | '/devices'
    | '/docs'
    | '/learn'
    | '/modules'
    | '/responsible-use'
    | '/shop'
    | '/software'
    | '/products/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CommunityRoute: typeof CommunityRoute
  DevicesRoute: typeof DevicesRoute
  DocsRoute: typeof DocsRoute
  LearnRoute: typeof LearnRoute
  ModulesRoute: typeof ModulesRoute
  ResponsibleUseRoute: typeof ResponsibleUseRoute
  ShopRoute: typeof ShopRoute
  SoftwareRoute: typeof SoftwareRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsible-use': {
      id: '/responsible-use'
      path: '/responsible-use'
      fullPath: '/responsible-use'
      preLoaderRoute: typeof ResponsibleUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software': {
      id: '/software'
      path: '/software'
      fullPath: '/software'
      preLoaderRoute: typeof SoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CommunityRoute: CommunityRoute,
  DevicesRoute: DevicesRoute,
  DocsRoute: DocsRoute,
  LearnRoute: LearnRoute,
  ModulesRoute: ModulesRoute,
  ResponsibleUseRoute: ResponsibleUseRoute,
  ShopRoute: ShopRoute,
  SoftwareRoute: SoftwareRoute,
  ProductsSlugRoute: ProductsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
